version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: poe_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: poe_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - poe_db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: poe_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - poe_redis_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Podmanfile
    container_name: poe_backend
    depends_on:
      - db
      - redis
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"

volumes:
  poe_db_data:
  poe_redis_data:
